#!/bin/bash

cd /cromwell-executions/prsInteractivePipeline/e19113f6-fac5-4a4e-a92e-ffa47c07575d/call-createSummary/execution
tmpDir=$(mktemp -d "$PWD"/tmp.XXXXXX)
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"


(
cd /cromwell-executions/prsInteractivePipeline/e19113f6-fac5-4a4e-a92e-ffa47c07575d/call-createSummary/execution

)


oute19113f6="${tmpDir}/out.$$" erre19113f6="${tmpDir}/err.$$"
mkfifo "$oute19113f6" "$erre19113f6"
trap 'rm "$oute19113f6" "$erre19113f6"' EXIT
touch '/cromwell-executions/prsInteractivePipeline/e19113f6-fac5-4a4e-a92e-ffa47c07575d/call-createSummary/execution/stdout' '/cromwell-executions/prsInteractivePipeline/e19113f6-fac5-4a4e-a92e-ffa47c07575d/call-createSummary/execution/stderr'
tee '/cromwell-executions/prsInteractivePipeline/e19113f6-fac5-4a4e-a92e-ffa47c07575d/call-createSummary/execution/stdout' < "$oute19113f6" &
tee '/cromwell-executions/prsInteractivePipeline/e19113f6-fac5-4a4e-a92e-ffa47c07575d/call-createSummary/execution/stderr' < "$erre19113f6" >&2 &
(
cd /cromwell-executions/prsInteractivePipeline/e19113f6-fac5-4a4e-a92e-ffa47c07575d/call-createSummary/execution


set -e

echo "Processing phenotype: type2Diabetes"
echo "Using pheno string: type 2 diabetes"
echo "With icd10: E11"

# Debug information
echo "Current working directory: $(pwd)"
echo "Current user: $(whoami)"
ls -la . || true

# Create the summary file to capture time stamp, phenotype substring, and icd10 code
ts=$(date +%Y%m%d_%H%M%S)


# Create summary file in working directory
summaryFile="summary.txt"
touch "${summaryFile}"
echo "timestamp of analysis: ${ts}" >> "${summaryFile}"
echo "phenotype analyzed: type2Diabetes" >> "${summaryFile}"
echo "phenotype substring filtered in participant.csv: type 2 diabetes" >> "${summaryFile}"
echo "icd 10 code used to define phenotype: E11" >> "${summaryFile}"
echo "user running workflow: $(whoami)" >> "${summaryFile}"

# Verify file was created
echo "Summary file contents:"
cat $summaryFile
)  > "$oute19113f6" 2> "$erre19113f6"
echo $? > /cromwell-executions/prsInteractivePipeline/e19113f6-fac5-4a4e-a92e-ffa47c07575d/call-createSummary/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/prsInteractivePipeline/e19113f6-fac5-4a4e-a92e-ffa47c07575d/call-createSummary/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/prsInteractivePipeline/e19113f6-fac5-4a4e-a92e-ffa47c07575d/call-createSummary/execution
sync


)
mv /cromwell-executions/prsInteractivePipeline/e19113f6-fac5-4a4e-a92e-ffa47c07575d/call-createSummary/execution/rc.tmp /cromwell-executions/prsInteractivePipeline/e19113f6-fac5-4a4e-a92e-ffa47c07575d/call-createSummary/execution/rc
