FROM ukb-base:V1

# Install PLINK and other data processing tools
# RUN apt-get update && apt-get install -y \
# plink1.9 \
# && rm -rf /var/lib/apt/lists/*

# Or install via conda if preferred
RUN conda install -n ukb_env -c bioconda plink

bash run_data_cleaning_workflow.sh

ENV STAGE="data_preprocessing"
