#!/bin/bash

cd /cromwell-executions/prsInteractivePipeline/c09bb7e1-b096-4981-8d4a-ed7cf6dba203/call-createSummary/execution
tmpDir=$(mktemp -d "$PWD"/tmp.XXXXXX)
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"


(
cd /cromwell-executions/prsInteractivePipeline/c09bb7e1-b096-4981-8d4a-ed7cf6dba203/call-createSummary/execution

)


outc09bb7e1="${tmpDir}/out.$$" errc09bb7e1="${tmpDir}/err.$$"
mkfifo "$outc09bb7e1" "$errc09bb7e1"
trap 'rm "$outc09bb7e1" "$errc09bb7e1"' EXIT
touch '/cromwell-executions/prsInteractivePipeline/c09bb7e1-b096-4981-8d4a-ed7cf6dba203/call-createSummary/execution/stdout' '/cromwell-executions/prsInteractivePipeline/c09bb7e1-b096-4981-8d4a-ed7cf6dba203/call-createSummary/execution/stderr'
tee '/cromwell-executions/prsInteractivePipeline/c09bb7e1-b096-4981-8d4a-ed7cf6dba203/call-createSummary/execution/stdout' < "$outc09bb7e1" &
tee '/cromwell-executions/prsInteractivePipeline/c09bb7e1-b096-4981-8d4a-ed7cf6dba203/call-createSummary/execution/stderr' < "$errc09bb7e1" >&2 &
(
cd /cromwell-executions/prsInteractivePipeline/c09bb7e1-b096-4981-8d4a-ed7cf6dba203/call-createSummary/execution


set -e

echo "Processing phenotype: type2Diabetes"
echo "Using pheno string: type 2 diabetes"
echo "With icd10: E11"

# Debug information
echo "Current working directory: $(pwd)"
echo "Current user: $(whoami)"
ls -la . || true

# Create the summary file to capture time stamp, phenotype substring, and icd10 code
ts=$(date +%Y%m%d_%H%M%S)

# Create summary file in working directory
summaryFile="summary.txt"
touch "${summaryFile}"
echo "timestamp of analysis: ${ts}" >> "${summaryFile}"
echo "phenotype analyzed: type2Diabetes" >> "${summaryFile}"
echo "phenotype substring filtered in participant.csv: type 2 diabetes" >> "${summaryFile}"
echo "icd 10 code used to define phenotype: E11" >> "${summaryFile}"

# Verify file was created
echo "Summary file contents:"
cat "${summaryFile}"
)  > "$outc09bb7e1" 2> "$errc09bb7e1"
echo $? > /cromwell-executions/prsInteractivePipeline/c09bb7e1-b096-4981-8d4a-ed7cf6dba203/call-createSummary/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/prsInteractivePipeline/c09bb7e1-b096-4981-8d4a-ed7cf6dba203/call-createSummary/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/prsInteractivePipeline/c09bb7e1-b096-4981-8d4a-ed7cf6dba203/call-createSummary/execution
sync


)
mv /cromwell-executions/prsInteractivePipeline/c09bb7e1-b096-4981-8d4a-ed7cf6dba203/call-createSummary/execution/rc.tmp /cromwell-executions/prsInteractivePipeline/c09bb7e1-b096-4981-8d4a-ed7cf6dba203/call-createSummary/execution/rc
