#!/usr/bin/env python3

# Keri Multerer 2025
# Unpenalized logistic regression:  PRSComp + covariates  vs
#                                   PRSComp + covariates + clinical measure
# 5-fold stratified cross-validation on the holdout set.
#
# Input file: {pheno_data}/scores/clinicalMeasures/combinedPRS.holdout.ClinicalMeasures.csv
#   Generated by clinical_measure_performance.py (must be run first).
#   Contains IID, PHENOTYPE, bin_combined (1-1000), raw clinical columns,
#   and {measure}_binary clinical columns.
#
# Covariates loaded from: {results_path}/covar.csv  (IID, age, SEX, PC1-PC10)
#
# Scaling note
# ------------
# bin_combined (1-1000) is z-scored per fold for numerical stability.
# Continuous covariates (age, PC1-PC10) are z-scored per training fold.
# SEX is binary (0/1) — left unscaled.
# Raw clinical measures are z-scored per fold in the logistic regression.
# _binary clinical columns are only used for NRI calculations (not scaled).

import os
import argparse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    roc_auc_score, precision_score, recall_score, roc_curve
)


# ---------------------------------------------------------------------------
# NRI helpers
# ---------------------------------------------------------------------------

def _count_reclassifications(old_risk, new_risk, is_case):
    """Pencina 2008 reclassification counter."""
    is_control = ~is_case
    up_cases      = int(np.sum(~old_risk[is_case]    &  new_risk[is_case]))
    down_cases    = int(np.sum( old_risk[is_case]    & ~new_risk[is_case]))
    up_controls   = int(np.sum(~old_risk[is_control] &  new_risk[is_control]))
    down_controls = int(np.sum( old_risk[is_control] & ~new_risk[is_control]))
    return {
        'up_cases': up_cases, 'down_cases': down_cases,
        'up_controls': up_controls, 'down_controls': down_controls,
        'n_cases': int(is_case.sum()), 'n_controls': int(is_control.sum()),
    }


def _nri_with_ci(old_risk, new_risk, is_case):
    """Return NRI components and 95% CI (Pencina 2008)."""
    counts     = _count_reclassifications(old_risk, new_risk, is_case)
    n_cases    = counts['n_cases']
    n_controls = counts['n_controls']

    nri_events     = (counts['up_cases']      - counts['down_cases'])    / n_cases
    nri_non_events = (counts['down_controls'] - counts['up_controls'])   / n_controls
    nri            = nri_events + nri_non_events

    se_ev  = np.sqrt(counts['up_cases']    + counts['down_cases'])    / n_cases
    se_ne  = np.sqrt(counts['up_controls'] + counts['down_controls']) / n_controls
    se_nri = np.sqrt(se_ev**2 + se_ne**2)

    return {
        'nri':            nri,
        'nri_events':     nri_events,
        'nri_non_events': nri_non_events,
        'ci_low':         nri - 1.96 * se_nri,
        'ci_high':        nri + 1.96 * se_nri,
        'se':             se_nri,
        'n_cases':        n_cases,
        'n_controls':     n_controls,
    }


def calculate_nri_from_probs(y_true, prob_ref, prob_new, threshold):
    """NRI comparing two probability arrays binarised at `threshold`."""
    return _nri_with_ci(
        old_risk=prob_ref >= threshold,
        new_risk=prob_new >= threshold,
        is_case=y_true.astype(bool),
    )


def youden_threshold(y_true, y_prob):
    """Probability threshold maximising sensitivity + specificity."""
    fpr, tpr, thresholds = roc_curve(y_true, y_prob)
    return float(thresholds[np.argmax(tpr - fpr)])


# ---------------------------------------------------------------------------
# data loading
# ---------------------------------------------------------------------------

COVAR_COLS = ['age', 'SEX', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5',
              'PC6', 'PC7', 'PC8', 'PC9', 'PC10']


def load_data(pheno_data, results_path, prs_col):
    """
    Load combinedPRS.holdout.ClinicalMeasures.csv, merge covariates from covar.csv.

    Returns
    -------
    df : pd.DataFrame
        Merged frame with IID, PHENOTYPE, prs_col, covariate cols,
        continuous clinical cols, _binary clinical cols.
    continuous_clinical_cols : list of str
        Raw continuous clinical measure columns used in logistic regression.
    binary_clinical_cols : list of str
        Corresponding {measure}_binary columns used for NRI.
    covariate_cols : list of str
        Covariate columns actually present after merge.
    prs_high_risk_col : str
        Binary PRS column: bin_combined >= 800 (top 20%).
    """
    # --- Clinical measures file (generated by clinical_measure_performance.py) ---
    clin_path = os.path.join(
        pheno_data, 'scores', 'clinicalMeasures',
        'combinedPRS.holdout.ClinicalMeasures.csv'
    )
    df = pd.read_csv(clin_path)
    print(f'Loaded {len(df)} rows from {clin_path}')

    # Phenotype is already recoded 0/1 in this file; verify
    phenotype_vals = set(df['PHENOTYPE'].dropna().unique())
    if phenotype_vals == {1, 2}:
        df['PHENOTYPE'] = df['PHENOTYPE'].replace({1: 0, 2: 1})
        print('Recoded PHENOTYPE 1→0 (control), 2→1 (case)')

    if prs_col not in df.columns:
        available = [c for c in df.columns if 'bin_' in c or 'scaled_prs' in c]
        raise ValueError(
            f"PRS column '{prs_col}' not found. "
            f"Available bin_/scaled_prs columns: {available}"
        )

    # Detect _binary clinical columns, then resolve paired continuous columns.
    # A continuous column exists when the base name (without _binary) is in the frame.
    binary_clinical_cols = [
        c for c in df.columns
        if c.endswith('_binary') and c != 'PHENOTYPE'
        and not any(x in c for x in ['high_risk', 'prs', 'bin_'])
    ]
    continuous_clinical_cols = [
        c[:-len('_binary')] for c in binary_clinical_cols
        if c[:-len('_binary')] in df.columns
    ]
    print(f'Continuous clinical columns (LR features): {continuous_clinical_cols}')
    print(f'Binary clinical columns (NRI):              {binary_clinical_cols}')

    # Binary PRS high-risk: bin_combined >= 800 (top 20% of 1-1000 range)
    PRS_HIGH_RISK_THRESHOLD = 800
    df['_prs_high_risk'] = (df[prs_col] >= PRS_HIGH_RISK_THRESHOLD).astype(int)
    prs_high_risk_col = '_prs_high_risk'
    n_hr = df['_prs_high_risk'].sum()
    print(f'PRS high-risk ({prs_col} >= {PRS_HIGH_RISK_THRESHOLD}): n={n_hr} '
          f'({100*n_hr/len(df):.1f}%)')

    # --- Covariates ---
    covar_path = os.path.join(results_path, 'covar.csv')
    df_cov = pd.read_csv(covar_path, usecols=['IID'] + COVAR_COLS)
    covariate_cols = [c for c in COVAR_COLS if c in df_cov.columns]

    df = df.merge(df_cov[['IID'] + covariate_cols], on='IID', how='left')

    # Drop rows missing any core column
    core = [prs_col] + covariate_cols + continuous_clinical_cols + binary_clinical_cols
    n_before = len(df)
    df.dropna(subset=core, inplace=True)
    print(f'Dropped {n_before - len(df)} rows with missing core values')
    print(f'Final N={len(df)}, cases={int(df["PHENOTYPE"].sum())}')

    return df, continuous_clinical_cols, binary_clinical_cols, covariate_cols, prs_high_risk_col


# ---------------------------------------------------------------------------
# logistic regression CV
# ---------------------------------------------------------------------------

def run_logistic_cv(df, prs_col, covariate_cols,
                    continuous_clinical_cols, binary_clinical_cols,
                    outcome_col='PHENOTYPE', n_splits=5, seed=42):
    """
    5-fold stratified CV.

    Model 1 (base):  bin_combined + covariate_cols
    Model 2 (+clin): base + one continuous clinical measure

    Columns z-scored per fold: bin_combined, age, PC1-PC10, clinical measures.
    SEX left unscaled (binary).
    NRI computed using the corresponding _binary clinical columns.

    Returns
    -------
    results : dict  keyed by continuous clinical col name (plus '_base')
    base_prob_pool : np.ndarray  pooled probabilities from base model
    clin_prob_pool : dict        pooled probabilities per clinical col
    """
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=seed)

    # All continuous features that need z-scoring (excluding SEX)
    continuous_base = [c for c in [prs_col] + covariate_cols if c != 'SEX']
    base_features   = [prs_col] + covariate_cols

    y = df[outcome_col].values
    base_prob_pool = np.full(len(df), np.nan)
    base_thresh_folds = []
    # keyed by continuous clinical col name
    clin_prob_pool = {c: np.full(len(df), np.nan) for c in continuous_clinical_cols}

    # Map continuous → binary col for NRI
    clin_to_binary = {
        cont: cont + '_binary'
        for cont in continuous_clinical_cols
        if cont + '_binary' in binary_clinical_cols
    }

    for fold_idx, (train_idx, test_idx) in enumerate(
            skf.split(np.arange(len(df)), y)):

        df_tr = df.iloc[train_idx].copy()
        df_te = df.iloc[test_idx].copy()

        # Scale all continuous base features (prs_col + continuous covariates)
        base_scaler = StandardScaler()
        df_tr[continuous_base] = base_scaler.fit_transform(df_tr[continuous_base])
        df_te[continuous_base] = base_scaler.transform(df_te[continuous_base])

        y_tr = df_tr[outcome_col].values
        y_te = df_te[outcome_col].values

        # Base model
        X_tr_base = df_tr[base_features].values
        X_te_base = df_te[base_features].values

        base_m = LogisticRegression(penalty=None, solver='lbfgs',
                                    max_iter=2000, random_state=seed)
        base_m.fit(X_tr_base, y_tr)
        base_prob_fold = base_m.predict_proba(X_te_base)[:, 1]
        base_prob_pool[test_idx] = base_prob_fold

        # Youden threshold from training predictions
        base_thresh_folds.append(
            youden_threshold(y_tr, base_m.predict_proba(X_tr_base)[:, 1])
        )

        # Augmented models: add one continuous clinical measure (z-scored on fold)
        for clin_col in continuous_clinical_cols:
            clin_scaler = StandardScaler()
            clin_tr = clin_scaler.fit_transform(df_tr[[clin_col]])
            clin_te = clin_scaler.transform(df_te[[clin_col]])

            X_tr_aug = np.hstack([X_tr_base, clin_tr])
            X_te_aug = np.hstack([X_te_base, clin_te])

            aug_m = LogisticRegression(penalty=None, solver='lbfgs',
                                       max_iter=2000, random_state=seed)
            try:
                aug_m.fit(X_tr_aug, y_tr)
                clin_prob_pool[clin_col][test_idx] = \
                    aug_m.predict_proba(X_te_aug)[:, 1]
            except Exception as exc:
                print(f'  [WARN] fold {fold_idx} {clin_col}: {exc}')
                clin_prob_pool[clin_col][test_idx] = base_prob_fold

    # Pool and compute metrics
    base_thresh = float(np.median(base_thresh_folds))
    print(f'\nMedian Youden threshold (base model): {base_thresh:.3f}')

    results = {}

    base_preds = (base_prob_pool >= base_thresh).astype(int)
    results['_base'] = {
        'auc':       roc_auc_score(y, base_prob_pool),
        'precision': precision_score(y, base_preds, zero_division=0),
        'recall':    recall_score(y, base_preds, zero_division=0),
    }
    b = results['_base']
    print(f'\n--- Base model (bin_combined + covariates) ---')
    print(f'  AUC={b["auc"]:.4f}  Precision={b["precision"]:.4f}  Recall={b["recall"]:.4f}')

    for clin_col in continuous_clinical_cols:
        prob_new  = clin_prob_pool[clin_col]
        preds     = (prob_new >= base_thresh).astype(int)

        # NRI uses binary classifications from the _binary column
        bin_col = clin_to_binary.get(clin_col)
        if bin_col and bin_col in df.columns:
            nri_d = calculate_nri_from_probs(y, base_prob_pool, prob_new, base_thresh)
        else:
            nri_d = {'nri': np.nan, 'nri_events': np.nan, 'nri_non_events': np.nan,
                     'ci_low': np.nan, 'ci_high': np.nan, 'se': np.nan,
                     'n_cases': int((y == 1).sum()), 'n_controls': int((y == 0).sum())}

        results[clin_col] = {
            'auc':       roc_auc_score(y, prob_new),
            'precision': precision_score(y, preds, zero_division=0),
            'recall':    recall_score(y, preds, zero_division=0),
            **nri_d,
        }
        m = results[clin_col]
        print(f'\n--- Augmented: + {clin_col} ---')
        print(f'  AUC={m["auc"]:.4f}  Precision={m["precision"]:.4f}  Recall={m["recall"]:.4f}')
        print(f'  NRI={m["nri"]:.4f}  95%CI=[{m["ci_low"]:.4f}, {m["ci_high"]:.4f}]')
        print(f'  NRI events={m["nri_events"]:.4f}  NRI non-events={m["nri_non_events"]:.4f}')

    return results, base_prob_pool, clin_prob_pool


# ---------------------------------------------------------------------------
# plotting
# ---------------------------------------------------------------------------

def plot_auc_comparison(results, figPath, prs_col_label='PRSComp'):
    """Horizontal bar chart: AUC for PRSComp + clinical vs PRSComp alone."""
    base_auc  = results['_base']['auc']
    clin_keys = [k for k in results if k != '_base']
    labels    = [k.replace('_', ' ') for k in clin_keys]
    aucs      = [results[k]['auc'] for k in clin_keys]

    fig, ax = plt.subplots(figsize=(7, 0.7 * len(clin_keys) + 2))
    colors = ['#BA7517' if a > base_auc else '#378ADD' for a in aucs]

    y_pos = np.arange(len(labels))
    ax.barh(y_pos, aucs, color=colors, height=0.5, zorder=2)
    ax.axvline(base_auc, color='#2C2C2A', linewidth=1.4, linestyle='--',
               label=f'{prs_col_label} alone (AUC={base_auc:.3f})')

    for i, a in enumerate(aucs):
        ax.text(a + 0.002, i, f'{a:.3f}', va='center', fontsize=9)

    ax.set_yticks(y_pos)
    ax.set_yticklabels(labels, fontsize=10)
    ax.set_xlabel('AUC (5-fold CV)', fontsize=11)
    ax.set_title(f'AUC: {prs_col_label} + clinical measure\nvs {prs_col_label} alone',
                 fontsize=12, pad=10)
    ax.legend(fontsize=9, frameon=False)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    all_aucs = aucs + [base_auc]
    ax.set_xlim(max(0, min(all_aucs) - 0.05), min(1, max(all_aucs) + 0.06))

    fig.tight_layout()
    out = os.path.join(figPath, 'auc_prs_vs_prs_plus_clinical.png')
    fig.savefig(out, dpi=300, bbox_inches='tight')
    plt.close(fig)
    print(f'\nAUC comparison plot saved to {out}')


def plot_nri_forest_lr(results, figPath):
    """
    Forest plot of NRI (logistic regression augmented vs base model)
    with 95% CI for each clinical measure.
    """
    clin_keys = [k for k in results if k != '_base']
    labels    = [k.replace('_', ' ') for k in clin_keys]
    nris      = [results[k]['nri']    for k in clin_keys]
    ci_los    = [results[k]['ci_low'] for k in clin_keys]
    ci_his    = [results[k]['ci_high'] for k in clin_keys]

    fig, ax = plt.subplots(figsize=(7, 0.7 * len(clin_keys) + 2))
    y_pos   = np.arange(len(labels))

    ax.errorbar(
        nris, y_pos,
        xerr=[np.array(nris) - np.array(ci_los),
              np.array(ci_his) - np.array(nris)],
        fmt='none', color='#2C2C2A', capsize=4, linewidth=1.2, zorder=3
    )
    colors = ['#BA7517' if n > 0 else '#378ADD' for n in nris]
    for i, (n, c) in enumerate(zip(nris, colors)):
        ax.scatter(n, i, color=c, s=70, zorder=4)

    ax.axvline(0, color='#2C2C2A', linewidth=1, linestyle='--', alpha=0.5)
    ax.set_yticks(y_pos)
    ax.set_yticklabels(labels, fontsize=10)
    ax.set_xlabel('NRI vs PRSComp alone (95% CI)', fontsize=11)
    ax.set_title(
        'Net Reclassification Improvement\n'
        '(PRSComp + covariates + clinical measure vs PRSComp + covariates)',
        fontsize=11, pad=8
    )
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    fig.tight_layout()

    out = os.path.join(figPath, 'nri_forest_lr_prs_plus_clinical.png')
    fig.savefig(out, dpi=300, bbox_inches='tight')
    plt.close(fig)
    print(f'NRI forest (LR) plot saved to {out}')


def plot_nri_forest_prs_vs_clinical(df, binary_clinical_cols, prs_high_risk_col,
                                    figPath, prs_label='ePRSCombined'):
    """
    Two-panel forest plot: NRI of ePRSCombined binary vs each clinical measure binary.

    Left panel  — Overall (all holdout samples)
    Right panel — Within clinically low-risk group ({measure}_binary == 0)

    Reference classifier: clinical measure binary (old)
    New classifier:       ePRSCombined binary  (new)
    """
    panels = [
        ('Overall',                        None),
        ('Within clinically low-risk group', 'low'),
    ]
    fig, axes = plt.subplots(1, 2, figsize=(12, 0.6 * len(binary_clinical_cols) + 3),
                             sharey=True)

    y_pos  = np.arange(len(binary_clinical_cols))
    labels = [c.replace('_binary', '').replace('_', ' ') for c in binary_clinical_cols]

    all_records = []

    for ax, (panel_title, panel_tag) in zip(axes, panels):
        nris, ci_los, ci_his, colors = [], [], [], []

        for clin_col in binary_clinical_cols:
            if panel_tag == 'low':
                sub = df[df[clin_col] == 0]
            else:
                sub = df

            if len(sub) == 0 or sub['PHENOTYPE'].nunique() < 2:
                nris.append(np.nan); ci_los.append(np.nan); ci_his.append(np.nan)
                colors.append('#AAAAAA')
                continue

            res = _nri_with_ci(
                old_risk=sub[clin_col].astype(bool),
                new_risk=sub[prs_high_risk_col].astype(bool),
                is_case=sub['PHENOTYPE'] == 1,
            )
            nris.append(res['nri'])
            ci_los.append(res['ci_low'])
            ci_his.append(res['ci_high'])
            colors.append('#BA7517' if res['nri'] > 0 else '#378ADD')

            all_records.append({
                'panel':          panel_title,
                'clinical_var':   clin_col,
                'nri':            res['nri'],
                'nri_events':     res['nri_events'],
                'nri_non_events': res['nri_non_events'],
                'ci_low':         res['ci_low'],
                'ci_high':        res['ci_high'],
                'n_cases':        res['n_cases'],
                'n_controls':     res['n_controls'],
            })

        xerr_lo = np.where(np.isnan(nris), 0, np.array(nris) - np.array(ci_los))
        xerr_hi = np.where(np.isnan(nris), 0, np.array(ci_his) - np.array(nris))

        ax.errorbar(
            nris, y_pos,
            xerr=[np.abs(xerr_lo), np.abs(xerr_hi)],
            fmt='none', color='#2C2C2A', capsize=4, linewidth=1.2, zorder=3
        )
        for i, (n, c) in enumerate(zip(nris, colors)):
            if not np.isnan(n):
                ax.scatter(n, i, color=c, s=70, zorder=4, marker='D')

        ax.axvline(0, color='#2C2C2A', linewidth=1, linestyle='--', alpha=0.5)
        ax.set_yticks(y_pos)
        ax.set_yticklabels(labels if ax is axes[0] else [], fontsize=10)
        ax.set_xlabel('NRI (95% CI)', fontsize=11)
        ax.set_title(panel_title, fontsize=11, pad=8)
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)

    fig.suptitle(
        f'NRI of {prs_label} vs clinical measure\n'
        f'(reference: clinical binary; new: {prs_label} high-risk)',
        fontsize=12, y=1.02
    )
    fig.tight_layout()

    out = os.path.join(figPath, 'nri_forest_ePRSCombined_vs_clinical.png')
    fig.savefig(out, dpi=300, bbox_inches='tight')
    plt.close(fig)
    print(f'NRI forest (ePRSCombined vs clinical) saved to {out}')

    return pd.DataFrame(all_records)


# ---------------------------------------------------------------------------
# results export
# ---------------------------------------------------------------------------

def export_results(results, nri_prs_df, figPath, pheno):
    rows = []
    for k, v in results.items():
        row = {'model': k}
        row.update(v)
        rows.append(row)
    lr_out = os.path.join(figPath, f'logistic_regression_results.{pheno}.csv')
    pd.DataFrame(rows).to_csv(lr_out, index=False)
    print(f'LR results saved to {lr_out}')

    if nri_prs_df is not None and len(nri_prs_df):
        nri_out = os.path.join(figPath, f'nri_ePRSCombined_vs_clinical.{pheno}.csv')
        nri_prs_df.to_csv(nri_out, index=False)
        print(f'NRI (ePRS vs clinical) results saved to {nri_out}')


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def run_logistic_analysis(pheno, pheno_data, results_path, prs_col, n_splits=5):
    figPath = os.path.join(pheno_data, 'figures', 'clinicalFigures')
    os.makedirs(figPath, exist_ok=True)

    df, continuous_clinical_cols, binary_clinical_cols, covariate_cols, prs_high_risk_col = \
        load_data(pheno_data, results_path, prs_col)

    # Logistic regression CV (continuous clinical cols as features, binary for NRI)
    results, base_prob, clin_probs = run_logistic_cv(
        df, prs_col, covariate_cols,
        continuous_clinical_cols, binary_clinical_cols,
        outcome_col='PHENOTYPE', n_splits=n_splits
    )

    plot_auc_comparison(results, figPath, prs_col_label=prs_col)
    plot_nri_forest_lr(results, figPath)

    # NRI forest: ePRSCombined binary vs each clinical measure binary
    nri_prs_df = plot_nri_forest_prs_vs_clinical(
        df, binary_clinical_cols, prs_high_risk_col, figPath,
        prs_label='ePRSCombined'
    )

    export_results(results, nri_prs_df, figPath, pheno)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Logistic regression: PRSComp + covariates vs + clinical measure'
    )
    parser.add_argument('--pheno_data',   help='Path to combinedAnalysis directory')
    parser.add_argument('--pheno',        help='Phenotype name (e.g. type2Diabetes)')
    parser.add_argument('--results_path', help='Path to results directory')
    parser.add_argument('--prs_col',      default='bin_combined',
                        help='PRS column name (default: bin_combined, range 1-1000)')
    parser.add_argument('--n_splits',     type=int, default=5,
                        help='Number of CV folds (default: 5)')
    args = parser.parse_args()

    pheno        = args.pheno        or os.environ.get('PHENO')
    pheno_data   = args.pheno_data   or os.environ.get('PHENO_DATA')
    results_path = args.results_path or os.environ.get('RESULTS_PATH')
    prs_col      = args.prs_col      or os.environ.get('PRS_COL', 'bin_combined')

    if not all([pheno, pheno_data, results_path]):
        raise ValueError(
            'Provide --pheno, --pheno_data, --results_path '
            '(or PHENO/PHENO_DATA/RESULTS_PATH env vars).'
        )

    run_logistic_analysis(pheno, pheno_data, results_path, prs_col, args.n_splits)
