#!/bin/bash

cd /cromwell-executions/prsInteractivePipeline/ed5b4106-fa53-4fb2-b21d-3c7f20acd864/call-createSummary/execution
tmpDir=$(mktemp -d "$PWD"/tmp.XXXXXX)
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"


(
cd /cromwell-executions/prsInteractivePipeline/ed5b4106-fa53-4fb2-b21d-3c7f20acd864/call-createSummary/execution

)


outed5b4106="${tmpDir}/out.$$" erred5b4106="${tmpDir}/err.$$"
mkfifo "$outed5b4106" "$erred5b4106"
trap 'rm "$outed5b4106" "$erred5b4106"' EXIT
touch '/cromwell-executions/prsInteractivePipeline/ed5b4106-fa53-4fb2-b21d-3c7f20acd864/call-createSummary/execution/stdout' '/cromwell-executions/prsInteractivePipeline/ed5b4106-fa53-4fb2-b21d-3c7f20acd864/call-createSummary/execution/stderr'
tee '/cromwell-executions/prsInteractivePipeline/ed5b4106-fa53-4fb2-b21d-3c7f20acd864/call-createSummary/execution/stdout' < "$outed5b4106" &
tee '/cromwell-executions/prsInteractivePipeline/ed5b4106-fa53-4fb2-b21d-3c7f20acd864/call-createSummary/execution/stderr' < "$erred5b4106" >&2 &
(
cd /cromwell-executions/prsInteractivePipeline/ed5b4106-fa53-4fb2-b21d-3c7f20acd864/call-createSummary/execution


set -e

echo "Processing phenotype: type2Diabetes"
echo "Using pheno string: type 2 diabetes"
echo "With icd10: E11"

# Debug information
echo "Current working directory: $(pwd)"
echo "Current user: $(whoami)"
ls -la . || true

# Create the summary file to capture time stamp, phenotype substring, and icd10 code
ts=$(date +%Y%m%d_%H%M%S)



# Create summary file in working directory
summaryFile="summary.txt"
touch "${summaryFile}"
echo "timestamp of analysis: ${ts}" >> "${summaryFile}"
echo "phenotype analyzed: type2Diabetes" >> "${summaryFile}"
echo "phenotype substring filtered in participant.csv: type 2 diabetes" >> "${summaryFile}"
echo "icd 10 code used to define phenotype: E11" >> "${summaryFile}"
echo "user running workflow: $(whoami)" >> "${summaryFile}"

# Verify file was created
echo "Summary file contents:"
cat $summaryFile
)  > "$outed5b4106" 2> "$erred5b4106"
echo $? > /cromwell-executions/prsInteractivePipeline/ed5b4106-fa53-4fb2-b21d-3c7f20acd864/call-createSummary/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/prsInteractivePipeline/ed5b4106-fa53-4fb2-b21d-3c7f20acd864/call-createSummary/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/prsInteractivePipeline/ed5b4106-fa53-4fb2-b21d-3c7f20acd864/call-createSummary/execution
sync


)
mv /cromwell-executions/prsInteractivePipeline/ed5b4106-fa53-4fb2-b21d-3c7f20acd864/call-createSummary/execution/rc.tmp /cromwell-executions/prsInteractivePipeline/ed5b4106-fa53-4fb2-b21d-3c7f20acd864/call-createSummary/execution/rc
